[project]
name = "mcp-istio"
version = "0.1.0"
description = "Istio Service Mesh MCP Server"
license = "Apache-2.0"
authors = [
  { name = "CNOE Contributors", email = "cnoe@example.com" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastmcp==2.13.3",
  "kubernetes==31.0.0",
  "mcp==1.21.0",
  "pydantic==2.12.5",
  "python-dotenv==1.2.1",
  "pyyaml==6.0.2",
]

[project.scripts]
mcp-istio = "mcp_istio.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
