[project]
name = "mcp-azuredevops"
version = "0.1.0"
description = "Azure DevOps MCP Server"
license = "Apache-2.0"
authors = [
  { name = "CNOE Contributors", email = "cnoe@example.com" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastmcp==2.13.3",
  "httpx==0.28.1",
  "mcp==1.21.0",
  "pydantic==2.12.5",
  "python-dotenv==1.2.1",
]

[project.scripts]
mcp-azuredevops = "mcp_azuredevops.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
