{{- if and (or (ne (default "multi-agent" .Values.global.deploymentMode) "single-node") .Values.remoteAgent) .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent.serviceAccountName" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
