name: ğŸ“¦ Publish Helm Chart to GHCR

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - helm/**

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Push Helm Chart to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: ğŸ” Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: ğŸ“ Update image.tag in values.yaml
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"
          yq e -i '.image.tag = strenv(TAG_VERSION)' helm/${{ github.event.repository.name }}/values.yaml
        env:
          TAG_VERSION: ${{ github.ref_name }}

      - name: ğŸ“¦ Package Helm Chart
        run: |
          helm dependency update helm/${{ github.event.repository.name }}
          helm package helm/${{ github.event.repository.name }} --destination ./

      - name: ğŸš€ Push Chart to GHCR
        run: |
          CHART_VERSION=$(helm show chart ./${{ github.event.repository.name }}-*.tgz | grep '^version:' | awk '{print $2}')
          helm push ./${{ github.event.repository.name }}-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts
