{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/{{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "mongodb.fullname" . }}-external-secret
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "mongodb.fullname" . }}-secret
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        conversionStrategy: {{ .remoteRef.conversionStrategy | default "Default" }}
        decodingStrategy: {{ .remoteRef.decodingStrategy | default "None" }}
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
    {{- end }}
{{- end }}
