{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-secret
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.auth.database | quote }}
{{- end }}
