[project]
name = "ingestors"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "subbaksh@cisco.com" }
]
requires-python = ">=3.13, <4.0"
dependencies = [
    "aiohttp>=3.13.2",
    "aiohttp-retry>=2.9.1",
    "beautifulsoup4>=4.14.2",
    "boto3>=1.38.38",
    "common",
    "fastapi[standard]>=0.121.2",
    "kubernetes>=33.1.0",
    "langchain>=1.0.7",
    "langchain-text-splitters>=1.0.0",
    "lxml>=6.0.2",
    "python-dotenv>=1.1.0",
    "redis>=7.0.1",
    "requests>=2.32.0",
    "slack-sdk>=3.38.0",
]

[project.scripts]
ingestors = "ingestors:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
common = { path = "../common" }
